### ISSUE TITLE
Errors don't fail the build on JDK 8

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/deptective#41]

**Comment by tbsfrdrch** [comment]
Can you tell how to reproduce this behaviour?

After applying a local fix for #47 I was building deptective with OpenJDK 11.0.3 using `mvn clean install` in the project's root folder, then switched to OpenJDK 8 1.8.0_212 and finally ran `./gradlew build` in the integration-test folder. The build failed as expected.

**Comment by gunnarmorling** [comment]
Can you try to run the integration test build with Maven instead of Gradle? That's how where I noticed this.

**Comment by tbsfrdrch** [comment]
Executing the integration-test build with Maven and Java 8 only worked after removing the enforcer plugin configuration from the aggregator project (to get rid of the limitation of having to use Java >= 11).

After doing that a `mvn clean package` indeed resulted in a non-failing build that writes the dependency violations as warnings to the log, but the reason for that seems to be the configuration within integration-test/pom.xml:
`-Xplugin:Deptective reporting_policy=WARN`

After switching that option to ERROR, even the Maven build breaks as expected.

No bug with Java 8 as far as I can tell.

**Comment by tbsfrdrch** [comment]
During my attempt to configure Deptective for one of my projects, I managed to provoke a successful build now, even though dependency violations exist and `reporting_policy` is configured as `ERROR`.

The problem seems to occur only with JDK 8 if in addition to Deptective another annotation processor is being executed.

To reproduce it
- switch to JDK 8,
- add the following dependency to [integration-test/build.gradle](https://github.com/moditect/deptective/blob/2309627bde584595b9cd25db74be73c4d1ca690e/integration-test/build.gradle#L12):
`annotationProcessor 'org.projectlombok:lombok:1.18.6'`
- invoke `./gradlew clean compileJava`

After switching to Java 11 or removing the Lombok dependency again, the build breaks again as expected.

@gunnarmorling do you have any idea what could be the reason for this behaviour or any hint of how I could fix it?

**Comment by tbsfrdrch** [comment]
After some quite extensive debugging of the Java 8 Compiler itself I was able to spot the root cause of the aforementioned problem. 

###  Analysis results
In it's init method the Deptective plugin grab's a Log object from the JavacTask's context and passes that very instance to all the internal Deptective components. The problem is, whenever an annotation processor is involved in the compilation process, a Log object instance different than that cached by Deptective is used to determine the final error count by the compiler, which explains why the errors reported by Deptective don't let the build fail in this case.

The relevant code pieces can be found here:
* [an additional JavaCompiler object](http://hg.openjdk.java.net/jdk8/jdk8/langtools/file/1ff9d5118aae/src/share/classes/com/sun/tools/javac/main/JavaCompiler.java#l1173) with its own Log instance is created when annotation processing is involved
* that new compiler object is [set as a delegate compiler object](
http://hg.openjdk.java.net/jdk8/jdk8/langtools/file/1ff9d5118aae/src/share/classes/com/sun/tools/javac/main/JavaCompiler.java#l858) onto the compiler object, which holds the Log object instance that Deptective is referring to
* in this case [the decision if the build has to terminate with an error](http://hg.openjdk.java.net/jdk8/jdk8/langtools/file/1ff9d5118aae/src/share/classes/com/sun/tools/javac/main/Main.java#l537) is solely based on the [error count of the delegate compiler and its Log object](http://hg.openjdk.java.net/jdk8/jdk8/langtools/file/1ff9d5118aae/src/share/classes/com/sun/tools/javac/main/JavaCompiler.java#l572). Any errors set by Deptective in the "outer" compiler's Log object will be ignored 

### Solution
To solve the problem Deptective can hold a reference to the JavacProcessingEnvironment and dynamically retrieve the correct Log instance from the currently active context whenever anything has to be logged.

@gunnarmorling please find the bugfix in my corresponding PR #51

**Comment by gunnarmorling** [comment]
Excellent, thank you so much, @tbsfrdrch!
